services:
  # Frontend only - API is external
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_BASE_URL: "https://simbisa-portal-demo-api.ipos.co.zw"
        REACT_APP_VERSION: "1.0.0"
        GENERATE_SOURCEMAP: "false"
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=https://simbisa-portal-demo-api.ipos.co.zw
      - REACT_APP_VERSION=1.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"