version: '3.8'

services:
  # API Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: production
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      # SSH Tunnel Configuration
      SSH_HOST: 41.191.232.15
      SSH_USERNAME: sa
      SSH_PASSWORD: s3rv3r5mx$
      REMOTE_BIND_HOST: 127.0.0.1
      REMOTE_BIND_PORT: 5437
      # Database Configuration
      DB_NAME: sensorsdb
      DB_USER: sa
      DB_PASSWORD: s3rv3r5mxdb
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped