version: '3.8'

services:
  # Development API Backend (hot reload)
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: development
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      # SSH Tunnel Configuration
      SSH_HOST: 41.191.232.15
      SSH_USERNAME: sa
      SSH_PASSWORD: s3rv3r5mx$
      REMOTE_BIND_HOST: 127.0.0.1
      REMOTE_BIND_PORT: 5437
      # Database Configuration
      DB_NAME: sensorsdb
      DB_USER: sa
      DB_PASSWORD: s3rv3r5mxdb
      JWT_SECRET: dev-jwt-secret-key
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]